// 十五五专题全题型模拟题
const quizData = [
  // ========== 填空题 ========== //
  { type: 'info', info: '【填空题 共40题，每题2分】' },
  { type: 'fill', question: '“十五五”规划实施的时间范围是____年到____年。', answer: ['2026','2030'], explanation: '2026到2030年。' },
  { type: 'fill', question: '“十五五”时期的主线是锚定____发展新目标。', answer: ['中国式现代化'], explanation: '主线为锚定中国式现代化发展新目标。' },
  { type: 'fill', question: '“十五五”时期经济社会发展必须坚持____发展。', answer: ['高质量'], explanation: '坚持高质量发展。' },
  { type: 'fill', question: '2024年全社会研发经费投入占GDP比重达到____%。', answer: ['2.68'], explanation: '2.68%。' },
  { type: 'fill', question: '“十五五”时期要加快建设____能源体系。', answer: ['新型'], explanation: '新型能源体系。' },
  { type: 'fill', question: '“十五五”时期，国内市场建设目标是全国____大市场。', answer: ['统一'], explanation: '全国统一大市场。' },
  { type: 'fill', question: '“十五五”时期，文化建设目标是发展新时代____特色社会主义文化。', answer: ['中国'], explanation: '新时代中国特色社会主义文化。' },
  { type: 'fill', question: '“十五五”时期，绿色转型目标包括建____能源体系。', answer: ['新型'], explanation: '新型能源体系。' },
  { type: 'fill', question: '2024年深圳研发投入占GDP比重达____%。', answer: ['6.46'], explanation: '6.46%。' },
  { type: 'fill', question: '“十五五”时期，农业农村发展的经验借鉴自____工程。', answer: ['千万'], explanation: '千万工程。' },
  { type: 'fill', question: '“十五五”时期，区域协调发展的重点是____联动。', answer: ['区域'], explanation: '区域联动。' },
  { type: 'fill', question: '“十五五”时期，民生福祉的目标包括高质量____。', answer: ['就业'], explanation: '高质量就业。' },
  { type: 'fill', question: '“十五五”时期，探索延长____教育。', answer: ['义务'], explanation: '延长义务教育。' },
  { type: 'fill', question: '“十五五”时期，渐进式延迟____。', answer: ['退休'], explanation: '渐进式延迟退休。' },
  { type: 'fill', question: '“十五五”时期，国防军队建设的重点是____化融合发展。', answer: ['智能'], explanation: '智能化融合发展。' },
  { type: 'fill', question: '“十五五”时期，国际合作的重点是____一带一路。', answer: ['共建'], explanation: '共建一带一路。' },
  { type: 'fill', question: '“十五五”时期，科技创新要全面实施“____+”。', answer: ['人工智能'], explanation: '人工智能+。' },
  { type: 'fill', question: '“十五五”时期，产业体系要实现传统产业____和未来产业突围。', answer: ['升级'], explanation: '传统产业升级。' },
  { type: 'fill', question: '“十五五”时期，发展经济的着力点应放在____经济上。', answer: ['实体'], explanation: '实体经济。' },
  { type: 'fill', question: '“十五五”时期，国家安全首次专章部署，覆盖____、数据、AI等新兴领域。', answer: ['网络'], explanation: '网络、数据、AI等新兴领域。' },
  { type: 'fill', question: '2024年高技术制造业增加值比“十三五”末增长____%。', answer: ['42'], explanation: '42%。' },
  { type: 'fill', question: '“十五五”时期，国内市场要破“____式”竞争。', answer: ['内卷'], explanation: '破内卷式竞争。' },
  { type: 'fill', question: '“十五五”时期，区域协调发展要推进跨省____建设。', answer: ['通道'], explanation: '跨省通道建设。' },
  { type: 'fill', question: '“十五五”时期，省级____权扩大。', answer: ['用地'], explanation: '省级用地权扩大。' },
  { type: 'fill', question: '“十五五”时期，文化自信要激发全民族____。', answer: ['创新'], explanation: '激发全民族创新。' },
  { type: 'fill', question: '“十五五”时期，讲好____故事。', answer: ['中国'], explanation: '讲好中国故事。' },
  { type: 'fill', question: '“十五五”时期，绿色转型要实施地方行业____考核。', answer: ['碳'], explanation: '碳考核。' },
  { type: 'fill', question: '“十五五”时期，持续推进____防治攻坚。', answer: ['污染'], explanation: '污染防治攻坚。' },
  { type: 'fill', question: '“十五五”时期，推进生态系统____。', answer: ['优化'], explanation: '生态系统优化。' },
  { type: 'fill', question: '“十五五”时期，积极稳妥推进____达峰碳中和。', answer: ['碳'], explanation: '碳达峰碳中和。' },
  { type: 'fill', question: '“十五五”时期，推进高质量____。', answer: ['就业'], explanation: '高质量就业。' },
  { type: 'fill', question: '“十五五”时期，探索____式延迟退休。', answer: ['渐进'], explanation: '渐进式延迟退休。' },
  { type: 'fill', question: '“十五五”时期，推进____强国、航天强国、交通强国、网络强国。', answer: ['制造'], explanation: '制造强国等。' },
  { type: 'fill', question: '“十五五”时期，构建以先进制造业为骨干的____产业体系。', answer: ['现代化'], explanation: '现代化产业体系。' },
  { type: 'fill', question: '“十五五”时期，坚持扩大____这个战略基点。', answer: ['内需'], explanation: '扩大内需。' },
  { type: 'fill', question: '“十五五”时期，促进消费和____良性互动。', answer: ['投资'], explanation: '消费和投资良性互动。' },
  { type: 'fill', question: '“十五五”时期，发展新时代中国特色社会主义____。', answer: ['文化'], explanation: '中国特色社会主义文化。' },
  { type: 'fill', question: '“十五五”时期，推进____生产生活方式。', answer: ['绿色'], explanation: '绿色生产生活方式。' },
  { type: 'fill', question: '“十五五”时期，推进____循环利用。', answer: ['废钢'], explanation: '废钢循环利用。' },
  { type: 'fill', question: '“十五五”时期，累计建成超过____亿亩高标准农田。', answer: ['10'], explanation: '10亿亩高标准农田。' },
  { type: 'fill', question: '“十五五”时期，发电装机容量占全球____分之一。', answer: ['三'], explanation: '全球三分之一。' },
  { type: 'fill', question: '“十五五”时期，单位GDP能耗累计降低____%。', answer: ['11.6'], explanation: '11.6%。' },
  // ========== 单选题 ========== //
  { type: 'info', info: '【单项选择题 共20题，每题2分】' },
  { type: 'single', question: '“十五五”规划实施的时间范围是？', options: ['2021-2025年', '2026-2030年', '2025-2030年', '2020-2025年'], answer: [1], explanation: '2026-2030年。' },
  { type: 'single', question: '“十五五”时期我国发展的主线是什么？', options: ['经济建设', '科技创新', '锚定中国式现代化发展新目标', '绿色转型'], answer: [2], explanation: '锚定中国式现代化发展新目标。' },
  { type: 'single', question: '“十五五”规划建议首次明确的时期定位是？', options: ['开启新征程', '夯实基础、全面发力的关键时期', '经济转型期', '绿色发展期'], answer: [1], explanation: '夯实基础、全面发力的关键时期。' },
  { type: 'single', question: '“十五五”时期经济社会发展必须坚持的首要原则是？', options: ['坚持高质量发展', '坚持绿色转型', '坚持科技创新', '坚持文化自信'], answer: [0], explanation: '坚持高质量发展。' },
  { type: 'single', question: '2024年全社会研发经费投入占GDP比重达到多少？', options: ['1.5%', '2.68%', '3.5%', '4.2%'], answer: [1], explanation: '2.68%。' },
  { type: 'single', question: '“十五五”规划强调的八大支柱任务不包括？', options: ['产业体系', '科技创新', '绿色转型', '金融投机'], answer: [3], explanation: '不包括金融投机。' },
  { type: 'single', question: '“十五五”时期，国家安全首次专章部署，覆盖哪些领域？', options: ['传统安全', '网络、数据、AI等新兴领域', '经济安全', '文化安全'], answer: [1], explanation: '网络、数据、AI等新兴领域。' },
  { type: 'single', question: '2024年高技术制造业增加值比“十三五”末增长了多少？', options: ['10%', '25%', '42%', '60%'], answer: [2], explanation: '42%。' },
  { type: 'single', question: '“十五五”时期，发展经济的着力点应放在？', options: ['金融业', '实体经济', '房地产', '服务业'], answer: [1], explanation: '实体经济。' },
  { type: 'single', question: '“十五五”规划提出要加快建设哪种能源体系？', options: ['传统能源', '新型能源', '煤炭能源', '石油能源'], answer: [1], explanation: '新型能源体系。' },
  { type: 'single', question: '2024年我国企业研发投入占比超过？', options: ['50%', '60%', '77%', '90%'], answer: [2], explanation: '77%。' },
  { type: 'single', question: '“十五五”时期，国内市场建设的目标是？', options: ['内卷式竞争', '全国统一大市场', '地方保护主义', '区域分割'], answer: [1], explanation: '全国统一大市场。' },
  { type: 'single', question: '“十五五”时期，文化建设的目标是？', options: ['发展娱乐产业', '发展新时代中国特色社会主义文化', '发展外来文化', '发展网络文化'], answer: [1], explanation: '新时代中国特色社会主义文化。' },
  { type: 'single', question: '“十五五”时期，绿色转型的目标包括？', options: ['建新型能源体系', '实施地方行业碳考核', '推动高碳产业发展', 'A和B'], answer: [3], explanation: '建新型能源体系和实施地方行业碳考核。' },
  { type: 'single', question: '2024年深圳研发投入占GDP比重达？', options: ['2%', '4%', '6.46%', '8%'], answer: [2], explanation: '6.46%。' },
  { type: 'single', question: '“十五五”时期，农业农村发展的经验借鉴自？', options: ['千万工程', '乡村振兴', '农业现代化', '农业合作社'], answer: [0], explanation: '千万工程。' },
  { type: 'single', question: '“十五五”时期，区域协调发展的重点是？', options: ['区域联动', '跨省通道建设', '省级用地权扩大', '以上都是'], answer: [3], explanation: '以上都是。' },
  { type: 'single', question: '“十五五”时期，民生福祉的目标包括？', options: ['高质量就业', '探索延长义务教育', '渐进式延迟退休', '以上都是'], answer: [3], explanation: '以上都是。' },
  { type: 'single', question: '“十五五”时期，国防军队建设的重点是？', options: ['机械化', '信息化', '智能化融合发展', '传统化'], answer: [2], explanation: '智能化融合发展。' },
  { type: 'single', question: '“十五五”时期，国际合作的重点是？', options: ['一带一路', '贸易保护', '单边主义', '经济脱钩'], answer: [0], explanation: '一带一路。' },
  // ========== 多选题 ========== //
  { type: 'info', info: '【多项选择题 共20题，每题3分】' },
  { type: 'multiple', question: '“十五五”时期经济社会发展必须遵循哪些原则？', options: ['坚持党的全面领导', '坚持人民至上', '坚持高质量发展', '坚持全面深化改革'], answer: [0,1,2,3], explanation: '四项原则均需坚持。' },
  { type: 'multiple', question: '“十五五”时期高质量发展的八大支柱包括？', options: ['产业体系', '科技创新', '国内市场', '金融投机'], answer: [0,1,2], explanation: '不包括金融投机。' },
  { type: 'multiple', question: '“十五五”时期科技创新的重点包括？', options: ['教育-科技-人才一体化', '全面实施“人工智能+”', '发展娱乐产业', '关键核心技术攻关'], answer: [0,1,3], explanation: '不包括发展娱乐产业。' },
  { type: 'multiple', question: '“十五五”时期绿色转型的措施包括？', options: ['建新型能源体系', '实施地方行业碳考核', '推动高碳产业发展', '废钢循环利用'], answer: [0,1,3], explanation: '不包括高碳产业发展。' },
  { type: 'multiple', question: '“十五五”时期，安全保障包括哪些方面？', options: ['粮食安全', '能源安全', '产业基础安全', '网络安全'], answer: [0,1,2,3], explanation: '四项均为安全保障内容。' },
  { type: 'multiple', question: '“十五五”时期，文化建设的目标包括？', options: ['讲好中国故事', '激发全民族创新', '发展新时代中国特色社会主义文化', '发展外来文化'], answer: [0,1,2], explanation: '不包括发展外来文化。' },
  { type: 'multiple', question: '“十五五”时期，区域协调发展的措施包括？', options: ['区域联动', '跨省通道建设', '省级用地权扩大', '地方保护主义'], answer: [0,1,2], explanation: '不包括地方保护主义。' },
  { type: 'multiple', question: '“十五五”时期，民生福祉的目标包括？', options: ['高质量就业', '探索延长义务教育', '渐进式延迟退休', '降低社会保障'], answer: [0,1,2], explanation: '不包括降低社会保障。' },
  { type: 'multiple', question: '“十五五”时期，科技创新的成果包括？', options: ['人工智能', '量子科技', '载人航天', '传统农业'], answer: [0,1,2], explanation: '不包括传统农业。' },
  { type: 'multiple', question: '“十五五”时期，绿色发展成就包括？', options: ['森林覆盖率提高', '空气质量优良天数比例提升', '新能源发电装机规模超过煤电', '高碳排放增长'], answer: [0,1,2], explanation: '不包括高碳排放增长。' },
  { type: 'multiple', question: '“十五五”时期，国家安全覆盖哪些新兴领域？', options: ['网络', '数据', 'AI', '传统农业'], answer: [0,1,2], explanation: '不包括传统农业。' },
  { type: 'multiple', question: '“十五五”时期，推进制造强国包括哪些方向？', options: ['智能化', '绿色化', '融合化', '娱乐化'], answer: [0,1,2], explanation: '不包括娱乐化。' },
  { type: 'multiple', question: '“十五五”时期，国内市场建设目标包括？', options: ['破内卷式竞争', '建全国统一大市场', '地方保护主义', '区域分割'], answer: [0,1], explanation: '不包括地方保护主义和区域分割。' },
  { type: 'multiple', question: '“十五五”时期，绿色转型目标包括？', options: ['建新型能源体系', '实施地方行业碳考核', '高碳产业发展', '绿色生产生活方式'], answer: [0,1,3], explanation: '不包括高碳产业发展。' },
  { type: 'multiple', question: '“十五五”时期，科技创新要实现哪些突破？', options: ['人工智能', '量子科技', '载人航天', '娱乐产业'], answer: [0,1,2], explanation: '不包括娱乐产业。' },
  { type: 'multiple', question: '“十五五”时期，区域协调发展措施包括？', options: ['区域联动', '跨省通道建设', '省级用地权扩大', '地方保护主义'], answer: [0,1,2], explanation: '不包括地方保护主义。' },
  { type: 'multiple', question: '“十五五”时期，民生福祉目标包括？', options: ['高质量就业', '探索延长义务教育', '渐进式延迟退休', '降低社会保障'], answer: [0,1,2], explanation: '不包括降低社会保障。' },
  { type: 'multiple', question: '“十五五”时期，绿色发展成就包括？', options: ['森林覆盖率提高', '空气质量优良天数比例提升', '新能源发电装机规模超过煤电', '高碳排放增长'], answer: [0,1,2], explanation: '不包括高碳排放增长。' },
  { type: 'multiple', question: '“十五五”时期，国家安全覆盖哪些新兴领域？', options: ['网络', '数据', 'AI', '传统农业'], answer: [0,1,2], explanation: '不包括传统农业。' },
  // ========== 判断题 ========== //
  { type: 'info', info: '【判断题 共20题，每题1分】' },
  { type: 'judge', question: '“十五五”时期是基本实现社会主义现代化夯实基础、全面发力的关键时期。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期我国发展环境将更加简单和稳定。', answer: false, explanation: '判断为错误。' },
  { type: 'judge', question: '“十五五”时期要坚持高质量发展为首要任务。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '2024年我国企业研发投入占比低于50%。', answer: false, explanation: '判断为错误。' },
  { type: 'judge', question: '“十五五”时期要加快建设新型能源体系，推进绿色转型。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期文化建设目标是发展外来文化。', answer: false, explanation: '判断为错误。' },
  { type: 'judge', question: '“十五五”时期要坚持党的全面领导和人民至上。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期不重视科技创新。', answer: false, explanation: '判断为错误。' },
  { type: 'judge', question: '“十五五”时期要推进国防军队智能化融合发展。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期国际合作重点是贸易保护。', answer: false, explanation: '判断为错误。' },
  { type: 'judge', question: '“十五五”时期要推进高质量就业。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进绿色生产生活方式。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进废钢循环利用。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进生态系统优化。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进碳达峰碳中和。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进制造强国、航天强国、交通强国、网络强国。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要推进现代化产业体系。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要坚持扩大内需。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要促进消费和投资良性互动。', answer: true, explanation: '判断为正确。' },
  { type: 'judge', question: '“十五五”时期要发展新时代中国特色社会主义文化。', answer: true, explanation: '判断为正确。' }
];
