const quizData = [
  { type: 'info', info: '【填空题 共29题，每题1分】' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["2025年8月，观星酒店预订增长47%。"], explanation: '材料对应知识点：2025年8月，观星酒店预订增长47%。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["热门景区增幅超300%。"], explanation: '材料对应知识点：热门景区增幅超300%。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["观星+产业融合成新增长点。"], explanation: '材料对应知识点：观星+产业融合成新增长点。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["Z世代追求心灵治愈。"], explanation: '材料对应知识点：Z世代追求心灵治愈。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["宁夏\"星星的故乡\"IP。"], explanation: '材料对应知识点：宁夏"星星的故乡"IP。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["青海火星小镇成科普目地。"], explanation: '材料对应知识点：青海火星小镇成科普目地。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["Labubi潮玩代表。"], explanation: '材料对应知识点：Labubi潮玩代表。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["丑萌美学创新。"], explanation: '材料对应知识点：丑萌美学创新。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["原创设计与文化软实力。"], explanation: '材料对应知识点：原创设计与文化软实力。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["消费品以旧换新推进。"], explanation: '材料对应知识点：消费品以旧换新推进。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["2025年新能源汽车增长50%。"], explanation: '材料对应知识点：2025年新能源汽车增长50%。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["博物馆一票难求。"], explanation: '材料对应知识点：博物馆一票难求。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["8630万人次参观。"], explanation: '材料对应知识点：8630万人次参观。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["数字化展览新形式。"], explanation: '材料对应知识点：数字化展览新形式。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["人形机器人应用。"], explanation: '材料对应知识点：人形机器人应用。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["外卖平台竞争激烈。"], explanation: '材料对应知识点：外卖平台竞争激烈。' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["47%（增长率）"], explanation: '材料对应知识点：47%（增长率）' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["300%（增幅）"], explanation: '材料对应知识点：300%（增幅）' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["50%（销量增长）"], explanation: '材料对应知识点：50%（销量增长）' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["8630万人次（参观）"], explanation: '材料对应知识点：8630万人次（参观）' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["观星+模式"], explanation: '材料对应知识点：观星+模式' },
  { type: 'fill', question: '观点一 丑萌美学，____个性的反叛表达', answer: ["Z世代"], explanation: '观点一 丑萌美学，Z世代个性的反叛表达' },
  { type: 'fill', question: '观点一 ____与微冒险——Z世代的情感价值锚点', answer: ["心灵治愈"], explanation: '观点一 心灵治愈与微冒险——Z世代的情感价值锚点' },
  { type: 'fill', question: '不同文化语境中都能找到生长点，打破了____的地域局限', answer: ["潮玩IP"], explanation: '不同文化语境中都能找到生长点，打破了潮玩IP的地域局限' },
  { type: 'fill', question: '观点一 ____，Z世代个性的反叛表达', answer: ["丑萌美学"], explanation: '观点一 丑萌美学，Z世代个性的反叛表达' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["VR体验"], explanation: '材料对应知识点：VR体验' },
  { type: 'fill', question: '2025年，____火出圈', answer: ["人形机器人"], explanation: '2025年，人形机器人火出圈' },
  { type: 'fill', question: '快培育新质生产力，数字生活、____等新业态成为扩大内需的重要力量', answer: ["即时零售"], explanation: '快培育新质生产力，数字生活、即时零售等新业态成为扩大内需的重要力量' },
  { type: 'fill', question: '根据材料，补全下列知识点：____', answer: ["2009年：Z世代出生上限"], explanation: '材料对应知识点：2009年：Z世代出生上限' },
  { type: 'info', info: '【单选题 共0题，每题1分】' },
  { type: 'info', info: '【多选题 共0题，每题1分】' },
  { type: 'info', info: '【判断题 共20题，每题1分】' },
  { type: 'judge', question: '2025年8月，观星酒店预订增长47%。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '热门景区增幅超300%。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '观星+产业融合成新增长点。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: 'Z世代追求心灵治愈。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '宁夏"星星的故乡"IP。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '青海火星小镇成科普目地。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: 'Labubi潮玩代表。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '丑萌美学创新。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '原创设计与文化软实力。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '消费品以旧换新推进。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '2025年新能源汽车增长50%。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '博物馆一票难求。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '8630万人次参观。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '数字化展览新形式。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '人形机器人应用。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '外卖平台竞争激烈。', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '47%（增长率）', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '300%（增幅）', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '50%（销量增长）', answer: [1], explanation: '该表述在材料中出现，判断为正确。' },
  { type: 'judge', question: '8630万人次（参观）', answer: [1], explanation: '该表述在材料中出现，判断为正确。' }
];
